apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: {{ .Values.appname }}
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: yolo5-deployment
 minReplicas: 1
 maxReplicas: 2
 targetCPUUtilizationPercentage: 50