apiVersion: v1
kind: PersistentVolume
metadata:
  name: pro-pv-hasan
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0aa0afa1bc3a4a410
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pro-pvc-hasan
  namespace: hasan
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi



