apiVersion: v1
kind: Service
metadata:
  name: polybot-service
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: {{ .Values.MainPort }}
      targetPort: {{ .Values.MainPort }}